### ISSUE TITLE
cannot run knxd with ft12 on raspi2/jessie

### ISSUE THREAD

**Issue by knxhm** [knxd/knxd#112]
Hi,
I want to use knxd on raspi2/jessie with serial interface but it doesn't start correctly.
The strange things is I have 2 different error messages with same settings:

1.try
root@knxdfhem:/home/pi/knxd# knxd -t 0xffc -f 9 -u /tmp/eib -D -T -R -S -b ft12:/dev/ttyAMA0
Layer 3(01B37C60,5683E41E) Open
Layer 8(01B481E0,5683E41E) OpenLocalSocket /tmp/eib
Layer 8(01B481E0,5683E41E) LocalSocket opened
Layer 8(01B586F8,5683E41E) Open
Layer 8(01B586F8,5683E41E) Opened
Layer 3(01B37C60,5683E41E) registerLayer2 01B58720
Layer 3(01B37C60,5683E41E) registerLayer2 01B58720 = 1
Layer 2(01B89C38,5683E41E) Open
Layer 2(01B89C38,5683E41E) Opened
initialisation of backend 'ft12:/dev/ttyAMA0' failed: No such file or directory
2.try
root@knxdfhem:/home/pi/knxd# knxd -t 0xffc -f 9 -u /tmp/eib -D -T -R -S -b ft12:/dev/ttyAMA0
Layer 3(0123BC60,5683E433) Open
Layer 8(0124C1E0,5683E433) OpenLocalSocket /tmp/eib
Layer 8(0124C1E0,5683E433) LocalSocket opened
Layer 8(0125C6F8,5683E433) Open
Layer 8(0125C6F8,5683E433) Opened
Layer 3(0123BC60,5683E433) registerLayer2 0125C720
Layer 3(0123BC60,5683E433) registerLayer2 0125C720 = 1
Layer 2(0128DC38,5683E433) Open
Layer 2(0128DC38,5683E433) Opened
initialisation of backend 'ft12:/dev/ttyAMA0' failed

With strace:
...
open("/dev/ttyAMA0", O_RDWR|O_NOCTTY|O_NONBLOCK|O_SYNC) = 7
ioctl(7, TIOCGSERIAL, 0x209d678)        = 0
ioctl(7, TIOCGSERIAL, 0x7ef281f4)       = 0
ioctl(7, TIOCSSERIAL, 0x7ef281f4)       = 0
close(7)                                = 0
open("/dev/ttyAMA0", O_RDWR|O_NOCTTY)   = 7
ioctl(7, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B19200 -opost -isig -icanon -echo ...}) = 0
ioctl(7, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B19200 -opost -isig -icanon -echo ...}) = 0
ioctl(7, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B19200 -opost -isig -icanon -echo ...}) = 0
ioctl(7, SNDCTL_TMR_CONTINUE or SNDRV_TIMER_IOCTL_GPARAMS or TCSETSF, {B19200 -opost -isig -icanon -echo ...}) = 0
ioctl(7, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B19200 -opost -isig -icanon -echo ...}) = 0
clock_gettime(CLOCK_MONOTONIC, {23214, 421676309}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
gettimeofday({1451484587, 936557}, NULL) = 0
write(1, "Layer 2(020ADC38,5683E5AB) Open\n", 32Layer 2(020ADC38,5683E5AB) Open
) = 32
brk(0x20cf000)                          = 0x20cf000
clock_gettime(CLOCK_MONOTONIC, {23214, 422555259}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
gettimeofday({1451484587, 937420}, NULL) = 0
write(1, "Layer 2(020ADC38,5683E5AB) Opene"..., 34Layer 2(020ADC38,5683E5AB) Opened
) = 34
write(1, "initialisation of backend 'ft12:"..., 80initialisation of backend 'ft12:/dev/ttyAMA0' failed: No such file or directory
) = 80
exit_group(1)                           = ?
+++ exited with 1 +++

The device /dev/ttyAMA0 is there and unused:
root@knxdfhem:/home/pi/knxd# ls /dev/ttyAMA0 -l
crw-rw---- 1 root dialout 204, 64 Dec 30 14:43 /dev/ttyAMA0

When I use tpuarts instead ft12 the daemon starts, but its not communicating correctly, I see no events from knx bus.
root@knxdfhem:/home/pi/knxd# knxd -t 0xffc -f 9 -u /tmp/eib -D -T -R -S -b tpuarts:/dev/ttyAMA0
Layer 3(01543C60,5683E4E5) Open
Layer 8(015541E0,5683E4E5) OpenLocalSocket /tmp/eib
Layer 8(015541E0,5683E4E5) LocalSocket opened
Layer 8(015646F8,5683E4E5) Open
Layer 8(015646F8,5683E4E5) Opened
Layer 3(01543C60,5683E4E5) registerLayer2 01564720
Layer 3(01543C60,5683E4E5) registerLayer2 01564720 = 1
Layer 2(01585650,5683E4E5) Open
Layer 2(01585650,5683E4E5) Openend
Layer 3(01543C60,5683E4E5) registerLayer2 01585650
Layer 2(01585650,5683E4E5) open-reset(001): 01
Layer 3(01543C60,5683E4E5) registerLayer2 01585650 = 1
W00000020: EIBD should not run as root
Layer 3(01543C60,5683E4E5) L3 started

When I use my IP gateway instead of the serial interface knxd works apparently (but this is not what I want):
root@knxdfhem:/home/pi/knxd# knxd -t 0xffc -f 9 -u /tmp/eib -D -T -R -S -b ipt:172.22.22.33
Layer 3(00B63C60,5683E533) Open
Layer 8(00B741E0,5683E533) OpenLocalSocket /tmp/eib
Layer 8(00B741E0,5683E533) LocalSocket opened
Layer 8(00B846F8,5683E533) Open
Layer 8(00B846F8,5683E533) Opened
Layer 3(00B63C60,5683E533) registerLayer2 00B84720
Layer 3(00B63C60,5683E533) registerLayer2 00B84720 = 1
Layer 2(00BA5650,5683E533) Open
Layer 2(00BA5650,5683E533) Opened
Layer 3(00B63C60,5683E533) registerLayer2 00BA5650
Layer 3(00B63C60,5683E533) registerLayer2 00BA5650 = 1
W00000020: EIBD should not run as root
Layer 3(00B63C60,5683E533) L3 started
Layer 3(00B63C60,5683E537) Enqueue L_Data low from 1.1.57 to 1/1/80 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 3(00B63C60,5683E537) RecvData L_Data low from 1.1.57 to 1/1/80 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 8(00B846F8,5683E537) Send_Route L_Data low from 1.1.57 to 1/1/80 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 

Any help appreciated.

**Comment by smurfix** [comment]
Strange.
I'll have a look.

**Comment by knxhm** [comment]
Thanks.
Oh, one more thing I want to add: on my old raspi1 I have the same ft12 interface working well without issues. 
pi@eibpi ~ $ ps -ef | grep eibd
eibd      2603     1  0 08:21 ?        00:00:27 /usr/local/bin/eibd -d -D -T -R -S -i -u --eibaddr=1.1.128 ft12:/dev/ttyAMA0

**Comment by smurfix** [comment]
In src/libserver/layer2.cpp, line 51+52, try to remove this:
```
  if (! addAddress (0))
    return false;
```
I'll have to checke whether that has any unwanted side effects.

**Comment by smurfix** [comment]
… On second thought, revert that. Instead, update to the "test" branch in the knxd repo.

**Comment by knxhm** [comment]
Mh, it starts now with ft12 but it does not process bus events correctly, however it does something when I send something on the bus, this is the strace from this. I included some lines before I send the telegram, see comment in log below.

clock_gettime(CLOCK_MONOTONIC, {29960, 420250975}) = 0
fcntl64(7, F_GETFL)                     = 0x2 (flags O_RDWR)
fcntl64(7, F_GETFL)                     = 0x2 (flags O_RDWR)
select(8, [7], NULL, NULL, {0, 0})      = 0 (Timeout)
fcntl64(7, F_GETFL)                     = 0x2 (flags O_RDWR)
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29960, 421328676}) = 0
rt_sigpending([], 8)                    = 0
read(3, 0x828254, 128)                  = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGHUP, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, 8) = 0
rt_sigaction(SIGINT, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigaction(SIGTERM, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], ~[KILL STOP RTMIN RT_1], 8) = 0
select(8, [3 5 6 7], [], [], {0, 0})    = 0 (Timeout)
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigaction(SIGHUP, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGINT, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGTERM, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29960, 423323402}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29960, 423772357}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29960, 424212093}) = 0
rt_sigpending([], 8)                    = 0
read(3, 0x828254, 128)                  = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGHUP, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, 8) = 0
rt_sigaction(SIGINT, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigaction(SIGTERM, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], ~[KILL STOP RTMIN RT_1], 8) = 0
select(8, [3 5 6 7], [], [], NULL


output stops here after starting, then I send a telegram on knx bus



)      = 1 (in [7])
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigaction(SIGHUP, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGINT, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGTERM, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29965, 188619211}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
read(7, "h\n\nh\363)\274\21", 255)      = 8
fcntl64(7, F_GETFL)                     = 0x2 (flags O_RDWR)
fcntl64(7, F_GETFL)                     = 0x2 (flags O_RDWR)
select(8, [7], NULL, NULL, {0, 0})      = 0 (Timeout)
fcntl64(7, F_GETFL)                     = 0x2 (flags O_RDWR)
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29965, 234652271}) = 0
rt_sigpending([], 8)                    = 0
read(3, 0x828254, 128)                  = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGHUP, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, 8) = 0
rt_sigaction(SIGINT, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigaction(SIGTERM, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], ~[KILL STOP RTMIN RT_1], 8) = 0
select(8, [3 5 6 7], [], [], NULL)      = 1 (in [7])
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigaction(SIGHUP, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGINT, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGTERM, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29965, 243135544}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
read(7, "9\tP\341\0\201\335\26", 255)   = 8
write(7, "\345", 1)                     = 1
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29965, 247922073}) = 0
rt_sigpending([], 8)                    = 0
read(3, 0x828254, 128)                  = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGHUP, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, 8) = 0
rt_sigaction(SIGINT, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigaction(SIGTERM, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], ~[KILL STOP RTMIN RT_1], 8) = 0
select(7, [3 5 6], [], [], {0, 0})      = 0 (Timeout)
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigaction(SIGHUP, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGINT, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGTERM, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29965, 256338836}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29965, 259721729}) = 0
rt_sigpending([], 8)                    = 0
read(3, 0x828254, 128)                  = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGHUP, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, 8) = 0
rt_sigaction(SIGINT, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigaction(SIGTERM, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], ~[KILL STOP RTMIN RT_1], 8) = 0
select(7, [3 5 6], [], [], {0, 0})      = 0 (Timeout)
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigaction(SIGHUP, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGINT, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGTERM, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29965, 266730429}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
fcntl64(7, F_GETFL)                     = 0x2 (flags O_RDWR)
fcntl64(7, F_GETFL)                     = 0x2 (flags O_RDWR)
select(8, [7], NULL, NULL, {0, 0})      = 0 (Timeout)
fcntl64(7, F_GETFL)                     = 0x2 (flags O_RDWR)
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29965, 270707589}) = 0
rt_sigpending([], 8)                    = 0
read(3, 0x828254, 128)                  = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGHUP, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, 8) = 0
rt_sigaction(SIGINT, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigaction(SIGTERM, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], ~[KILL STOP RTMIN RT_1], 8) = 0
select(8, [3 5 6 7], [], [], {0, 0})    = 0 (Timeout)
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigaction(SIGHUP, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGINT, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
rt_sigaction(SIGTERM, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29965, 276752702}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, ~[KILL STOP RTMIN RT_1], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {29965, 279165341}) = 0
rt_sigpending([], 8)                    = 0
read(3, 0x828254, 128)                  = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGHUP, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_DFL, [], SA_RESTORER, 0x76c7d160}, 8) = 0
rt_sigaction(SIGINT, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigaction(SIGTERM, {0x76f5f8b0, ~[RTMIN RT_1], SA_RESTORER, 0x76c7d160}, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x76c7d160}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], ~[KILL STOP RTMIN RT_1], 8) = 0
select(8, [3 5 6 7], [], [], NULL^CLayer 3(00828C60,5684000C) Close
Layer 3(00828C60,5684000C) L3 stopping
Layer 8(008391E0,5684000C) StopServer
Layer 8(008391E0,5684000C) StopBaseServer
Layer 3(00828C60,5684000C) deregisterServer 008391E0 = 1
Layer 3(00828C60,5684000C) deregisterLayer2 00839204 = 0
Layer 8(008496F8,5684000C) Close
Layer 3(00828C60,5684000C) deregisterLayer2 00849720 = 1
Process 29471 detached
 <detached ...>

**Comment by smurfix** [comment]
That's where my abiity to help ends, as I don't have the hardware. You'll have to build knxd with debugging (i.e. CXXFLAGS="-g -O0") and trace packet reception with gdb.

Does sending work?

If you'd like, I could ssh to your system and figure out what's wrong. (Fortunately you have a second gateway, otherwise somebody would have to press a physical button for testing anything.)

**Comment by knxhm** [comment]
I am afraid I am not so good with gdb on a unknown software. But if you want to remote connect I really appreciate , I will prepare something. 
I understand you are also active in fhem forum and I could send you a PM there with  login credentials for you?

**Comment by smurfix** [comment]
Please email matthias@urlichs.de.

For remote access, best to use ssh. My key: 
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+UHhlPv5RKN3yH4p9LXH1x5m/H9i3C2d+e2jZ7FHhJQVeCm1AqY66YaVjwpgIp2P07F+Y9b0NLku7p8CvX4qhmKGCv9RDrfmfmEEsoQNpOgfOLzPNJ7EiEXDnoL/RkaiGohCrLMMBYRafqV7jOgGgpYZJtyfpCA/hTL+SsHtsNTqseglgaADMG0JN/H8VKTO9HnaFCWfOYzF1ayW+Kme/vq9909rxhYRh/63QnhBAHL0EFQni2WA7J+d+EMzGCZDEOeJki+3S++C9oB6tym9tLl7yMn43d23mr+PS5iV+iAG42LY+JY3m6RznTQtVjsOP0Gk+3eLYEShfy4R+QJYvja4Ut85rwSmrY7Rf8x87z5r1GO/Dmn7Gga5O/wRsXkRFtTj4YZl2RxCQ+B3kMG/AUcD7zzIpF+IsfrHbIOYcRcQPoxbNw7VENJcTygml8YALKl+fNiburw3Zfvb2JLgI3JXzsAiBcpcZNWT1B4aUSnXUx/CnJ6C1Qx1tlIQpHaMWLLokBoLows5mwjitMBQVTAEELY6xFUcliRrfBrY5qxEPexVuzmvw6o4GYnnT61RfnAFk+XOVAnThbW5rx/lVZFXiuljRRJiws0DY5PRgZZ67R+1hp22L3bpV6anDnLWjHGh3uoU4bF1m9SE2802D9G39VklziEkqC0ne6G4I/w== matthias@urlichs.de
```
Copy (as a single line) to ~/.ssh/authorized_keys.

**Comment by knxhm** [comment]
ok. see PM.

**Comment by KaneTW** [comment]
I'm getting the same error. I'll try bisecting and see what commit breaks it, because it works fine with eibd-0.0.5

**Comment by smurfix** [comment]
Found it. Current master should fix it. Will test shortly.

**Comment by KaneTW** [comment]
new master seems to crash with
```
Layer 2(01A7B6F0,5684B7E0) Open
Layer 2(01A7B6F0,5684B7E0) Opened
Layer 2(01A7B6F0,5684B7E0) OpenL2
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

but that might be a different issue.

**Comment by KaneTW** [comment]
Found it.
In https://github.com/knxd/knxd/blob/master/src/backend/ft12.cpp#L195
that should be an int, or failure isn't properly handled (the i > 0 check is vacuously true).

**Comment by KaneTW** [comment]
Or, nope. It doesn't crash now but it also still doesn't work.

**Comment by smurfix** [comment]
I saw that one too. On @knxhm's test system knxd (master branch) now works (tested by successfully receiving his periodic bus telegrams via "knxtool groupsocketlisten local:").

**Comment by KaneTW** [comment]
I rebooted the VM and it seems to work. Yay.

**Comment by smurfix** [comment]
Cool. Thanks for testing.

**Comment by knxhm** [comment]
Confirm it works. Great job. Thanks.
